# Generated by Django 3.2.12 on 2023-10-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profile_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
